### ISSUE TITLE
Bug:  Dependency unavailable

### ISSUE THREAD

**Issue by kcw-grunt** [jasonjrr/MVVM.Demo.SwiftUI#3]
## Problem
When trying the demo, the package was unavailable

| Snapshot |
|-----------|
|<img width="1002" alt="Screenshot 2023-12-03 at 10 20 26 PM" src="https://github.com/jasonjrr/MVVM.Demo.SwiftUI/assets/2899463/e969e995-2fb5-4ac5-ab59-b967e8e6fc1a">|

**Comment by kcw-grunt** [comment]
Resolved

**Comment by msuzoagu** [comment]
Hello! Just downloaded and getting the same error 
![Screenshot 2024-01-13 at 2 24 51 PM](https://github.com/jasonjrr/MVVM.Demo.SwiftUI/assets/5686704/8349bce2-a3a3-410a-8c00-05eafb1a2c27)
